on: push
name: Flutter CI
jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: codecov/codecov-action@v1.0.2
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{secrets.CODECOV_TOKEN}} 
          file: ./coverage/lcov.info 
